baseURL = 'https://chicago.harperreed.com/'
languageCode = 'en-us'
title = "Harper's Incomplete Chicago Guide"

disableKinds = ["taxonomy", "RSS", "sitemap", "robotsTXT"]


[Params]
description = "Places I like in Chicago. I've been here 25+ years and still forget half of them when people ask."
email = 'harper@modest.com'
name = 'Harper'
twitter = 'harper'
